# Generated by Django 5.2 on 2025-04-27 23:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('2G', '2G - GSM'), ('3G', '3G - UMTS'), ('4G', '4G - LTE')], max_length=10)),
                ('propagation_model', models.CharField(choices=[('OKUMURA_HATA', 'Okumura-Hata'), ('COST_231', 'COST-231')], max_length=20)),
                ('frequency', models.FloatField(help_text='Frequency in MHz')),
                ('antenna_height', models.FloatField(help_text='Antenna height in meters')),
                ('antenna_power', models.FloatField(help_text='Antenna power in dBm')),
                ('terrain_type', models.CharField(choices=[('URBAN', 'Urban'), ('SUBURBAN', 'Suburban'), ('RURAL', 'Rural'), ('OPEN', 'Open')], max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Antenna location (longitude, latitude)', srid=4326)),
                ('radius', models.FloatField(help_text='Simulation radius in kilometers')),
                ('population_density', models.FloatField(blank=True, help_text='Population density per square kilometer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_area', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Coverage area polygons', srid=4326)),
                ('coverage_percentage', models.FloatField(help_text='Percentage of area covered')),
                ('population_covered', models.IntegerField(blank=True, help_text='Estimated population covered', null=True)),
                ('signal_strength_data', models.JSONField(help_text='Signal strength data for visualization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation.simulation')),
            ],
        ),
    ]
