# Generated by Django 5.2 on 2025-07-01 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_alter_simulation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='simulation',
            name='coverage_area',
            field=models.FloatField(default=0, help_text='Coverage area in square kilometers'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='technology',
            field=models.CharField(blank=True, choices=[('2G', '2G - GSM'), ('3G', '3G - UMTS'), ('4G', '4G - LTE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='terrain_type',
            field=models.CharField(blank=True, choices=[('URBAN', 'Urban'), ('SUBURBAN', 'Suburban'), ('RURAL', 'Rural'), ('OPEN', 'Open')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['user', 'created_at'], name='simulation__user_id_734e13_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['technology'], name='simulation__technol_9b1466_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['terrain_type'], name='simulation__terrain_a6e78b_idx'),
        ),
    ]
