# Generated by Django 5.2 on 2025-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_alter_simulation_options_simulation_coverage_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='simulation',
            name='simulation__user_id_734e13_idx',
        ),
        migrations.RemoveIndex(
            model_name='simulation',
            name='simulation__technol_9b1466_idx',
        ),
        migrations.RemoveIndex(
            model_name='simulation',
            name='simulation__terrain_a6e78b_idx',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='coverage_area',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='terrain_type',
        ),
        migrations.AddField(
            model_name='simulationparameter',
            name='bandwidth',
            field=models.PositiveIntegerField(default=20, help_text='Bandwidth in MHz'),
        ),
        migrations.AddField(
            model_name='simulationparameter',
            name='beamforming',
            field=models.BooleanField(default=True, help_text='Enable beamforming'),
        ),
        migrations.AddField(
            model_name='simulationparameter',
            name='frequency_band',
            field=models.CharField(choices=[('n1', 'n1 (2100 MHz)'), ('n3', 'n3 (1800 MHz)'), ('n7', 'n7 (2600 MHz)'), ('n28', 'n28 (700 MHz)'), ('n78', 'n78 (3500 MHz)'), ('n258', 'n258 (26 GHz)'), ('n260', 'n260 (39 GHz)')], default='n78', help_text='5G Frequency Band', max_length=20),
        ),
        migrations.AddField(
            model_name='simulationparameter',
            name='mimo_layers',
            field=models.PositiveSmallIntegerField(choices=[(1, '1x1'), (2, '2x2'), (4, '4x4'), (8, '8x8')], default=4, help_text='Number of MIMO layers'),
        ),
        migrations.AddField(
            model_name='simulationparameter',
            name='numerology',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 (15 kHz)'), (1, '1 (30 kHz)'), (2, '2 (60 kHz)'), (3, '3 (120 kHz)')], default=1, help_text='5G Numerology (0-4)'),
        ),
        migrations.AddField(
            model_name='simulationparameter',
            name='subcarrier_spacing',
            field=models.PositiveIntegerField(choices=[(15, '15 kHz'), (30, '30 kHz'), (60, '60 kHz'), (120, '120 kHz')], default=30, help_text='Subcarrier spacing in kHz'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='connection_density',
            field=models.FloatField(blank=True, help_text='Connection density (devices/km²)', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='latency',
            field=models.FloatField(blank=True, help_text='End-to-end latency in ms', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='peak_data_rate',
            field=models.FloatField(blank=True, help_text='Peak data rate in Mbps', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='performance_metrics',
            field=models.JSONField(blank=True, help_text='Additional performance metrics', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='spectral_efficiency',
            field=models.FloatField(blank=True, help_text='Spectral efficiency in bps/Hz', null=True),
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='propagation_model',
            field=models.CharField(choices=[('OKUMURA_HATA', 'Okumura-Hata'), ('COST_231', 'COST-231'), ('COST_HATA', 'COST-Hata'), ('FREESPACE', 'Free Space Path Loss'), ('3GPP_UMa', '3GPP Urban Macrocell'), ('3GPP_UMi', '3GPP Urban Microcell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='technology',
            field=models.CharField(choices=[('2G', '2G - GSM'), ('3G', '3G - UMTS'), ('4G', '4G - LTE'), ('5G_NR', '5G NR - New Radio')], max_length=10),
        ),
    ]
