# Generated by Django 5.2 on 2025-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_alter_simulation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='battery_life',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated battery life in days', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='coverage_enhancement',
            field=models.FloatField(blank=True, help_text='Coverage enhancement in dB (NB-IoT: up to 20dB, LTE-M: up to 15dB)', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='downlink_data_rate',
            field=models.FloatField(blank=True, help_text='Downlink data rate in kbps', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='uplink_data_rate',
            field=models.FloatField(blank=True, help_text='Uplink data rate in kbps', null=True),
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='subcarrier_spacing',
            field=models.PositiveIntegerField(choices=[(3.75, '3.75 kHz (NB-IoT)'), (15, '15 kHz'), (30, '30 kHz'), (60, '60 kHz'), (120, '120 kHz')], default=30, help_text='Subcarrier spacing in kHz'),
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='technology',
            field=models.CharField(choices=[('2G', '2G - GSM'), ('3G', '3G - UMTS'), ('4G', '4G - LTE'), ('5G_NR', '5G NR - New Radio'), ('NB_IOT', 'NB-IoT'), ('LTE_M', 'LTE-M')], max_length=10),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='connection_density',
            field=models.FloatField(blank=True, help_text='Connection density (devices/km²) - NB-IoT: ~50k-100k, LTE-M: ~10k-50k', null=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='latency',
            field=models.FloatField(blank=True, help_text='End-to-end latency in ms (NB-IoT: ~1.6-10s, LTE-M: ~50-100ms)', null=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='peak_data_rate',
            field=models.FloatField(blank=True, help_text='Peak data rate in kbps (NB-IoT: ~250kbps, LTE-M: ~1Mbps)', null=True),
        ),
    ]
