# Generated by Django 5.2 on 2025-07-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_simulationresult_battery_life_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationparameter',
            name='beamforming',
        ),
        migrations.RemoveField(
            model_name='simulationparameter',
            name='frequency_band',
        ),
        migrations.RemoveField(
            model_name='simulationparameter',
            name='mimo_layers',
        ),
        migrations.RemoveField(
            model_name='simulationparameter',
            name='numerology',
        ),
        migrations.RemoveField(
            model_name='simulationparameter',
            name='subcarrier_spacing',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='battery_life',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='connection_density',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='coverage_enhancement',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='downlink_data_rate',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='peak_data_rate',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='performance_metrics',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='spectral_efficiency',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='uplink_data_rate',
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='bandwidth',
            field=models.FloatField(default=10.0, help_text='Bandwidth in MHz'),
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='propagation_model',
            field=models.CharField(choices=[('OKUMURA_HATA', 'Okumura-Hata'), ('COST_231', 'COST-231')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulationparameter',
            name='technology',
            field=models.CharField(choices=[('2G', '2G - GSM'), ('3G', '3G - UMTS'), ('4G', '4G - LTE')], max_length=10),
        ),
    ]
