# Generated by Django 5.2 on 2025-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0006_remove_simulationparameter_beamforming_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationparameter",
            name="bandwidth",
            field=models.FloatField(default=5.0, help_text="Bandwidth in MHz"),
        ),
    ]
