# Generated by Django 5.2 on 2025-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0007_alter_simulationparameter_bandwidth"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationparameter",
            name="h",
            field=models.FloatField(
                blank=True, help_text="Hauteur moyenne des bâtiments (m)", null=True
            ),
        ),
        migrations.AddField(
            model_name="simulationparameter",
            name="h_bs",
            field=models.FloatField(
                blank=True, help_text="Hauteur de la station de base (m)", null=True
            ),
        ),
        migrations.AddField(
            model_name="simulationparameter",
            name="h_ut",
            field=models.FloatField(
                blank=True, help_text="Hauteur de l'utilisateur (m)", null=True
            ),
        ),
        migrations.AddField(
            model_name="simulationparameter",
            name="los_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOS", "Line of Sight (LOS)"),
                    ("NLOS", "Non-Line of Sight (NLOS)"),
                ],
                help_text="Line of sight condition",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationparameter",
            name="scenario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UMa", "Urban Macro (UMa)"),
                    ("UMi", "Urban Micro (UMi)"),
                    ("RMa", "Rural Macro (RMa)"),
                    ("InH-Office", "Indoor Hotspot - Office"),
                    ("InH-ShoppingMall", "Indoor Hotspot - Shopping Mall"),
                ],
                help_text="5G deployment scenario",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationparameter",
            name="w",
            field=models.FloatField(
                blank=True, help_text="Largeur moyenne des routes (m)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="simulationparameter",
            name="propagation_model",
            field=models.CharField(
                choices=[
                    ("OKUMURA_HATA", "Okumura-Hata"),
                    ("COST_231", "COST-231"),
                    ("3GPP_TR_38901", "3GPP TR 38.901 (5G)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="simulationparameter",
            name="technology",
            field=models.CharField(
                choices=[
                    ("2G", "2G - GSM"),
                    ("3G", "3G - UMTS"),
                    ("4G", "4G - LTE"),
                    ("5G", "5G - NR (New Radio)"),
                ],
                max_length=10,
            ),
        ),
    ]
